apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novashop.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "novashop.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "novashop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.nextPublicApiUrl | quote }}
