apiVersion: v1
kind: Service
metadata:
  name: {{ include "novashop.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "novashop.labels" . | nindent 4 }}
    {{- include "novashop.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "novashop.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
