apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novashop-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: novashop-root
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: novashop
    novashop.io/deployment-target: ubuntu-k3s
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: novashop
  source:
    repoURL: https://github.com/nguyenlpn2015/NovaShop-GitOps.git
    targetRevision: main
    path: clusters/ubuntu-k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
