apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: novashop-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
