config:
  environment: development

backend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  tls:
    enabled: false
